config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"
  get 'admin', to: "static_pages#admin"

  scope :admin  do

    devise_for :users
    resources :users
    resources :roles

    resources :box_types
    resources :bag_types
    resources :pallet_types
    resources :package_types
    resources :count_types
    resources :delivery_places

    resources :greenhouses do
        get 'info' => 'greenhouses#info', as: 'info'
        get 'average-prices' => 'greenhouses#average_price_week', as: "average_price_week"
        resources :sales, except: :index do
          resources :manifests
          resources :collections_bills
        end
        resources :shipments
        resources :customers do
          resources :contacts
        end
        resources :products
        resources :colors
        resources :warehouses
        resources :custom_brokers

    end


    #Hash key => value
    #what the client see => what the system does, as: alias you can use in the system


   #Estas siguientes direcciones de PATCH se requieren para que se puedan actualizar
   #los modelos anidados
   patch '/greenhouses/:greenhouse_id/customers.:id' => 'customers#update'
   patch '/greenhouses/:greenhouse_id/products.:id' => 'products#update'
   patch '/greenhouses/:greenhouse_id/sales.:id' => 'sales#update'
   patch '/greenhouses/:greenhouse_id/colors.:id' => 'colors#update'
   patch '/greenhouses/:greenhouse_id/warehouses.:id' => 'warehouses#update'
   patch '/greenhouses/:greenhouse_id/sales/:sale_id/manifests.:id' => 'manifests#update'
   patch '/greenhouses/:greenhouse_id/custom_brokers.:id' => 'custom_brokers#update'
   patch '/greenhouses/:greenhouse_id/sales/:sale_id/collections_bills.:id' => 'collections_bills#update'


#Acción al cambiar de estados en la venta
    #get 'purshase_order_state_change' => 'sales#purshase_order_state_change', as: => :purshase_order_state_change
    get 'purshase_order_state_change', action: :purshase_order_state_change, controller: 'sales'
#Fin###########


#Acción al actualizar las anotaciones en el preview de la orden de compra. order.html.erbta
    post 'annotations_update' => 'sales#annotations_update'
#Fin###########

    #Acción que se manda a llamar para cargar los conteos adecuados para cada producto.
    get 'get_product_count_types' => 'count_types#get_product_count_types'
    #Fin de esta petición ajax que se llama desde _shipment_fields.html.erb

    #Acción que se manda a ejecutar la validación apropiada.
    get '/greenhouses/sales/is_unique' => 'sales#is_unique'
    post '/greenhouses/manifests/is_unique' => 'manifests#is_unique'
    #Fin de esta petición ajax que se llama desde sales/_form.html.erb

    # Ajax Request from customs_invoice preview
    post '/greenhouses/manifests/set_leyend' => 'manifests#set_leyend'

    post 'purshase_order/greenhouses/:greenhouse_id/sales/:sale_id' => 'sales#purshase_order', as: "purshase_order"
    get 'customs_billing/sales/:greenhouse_id/:sale_id' => 'sales#customs_bill', as: "customs_billing"
    get 'customs_bill/greenhouses/:greenhouse_id/sales/:sale_id' => 'manifests#new', as: 'customs'

    get 'manifests/customs_invoice' => 'manifests#to_customs_invoice', as: "to_customs_invoice"
    get 'collections_bills/invoice/:id' => 'collections_bills#to_invoice', as: "to_invoice"

    get 'collections_bill' => 'sales#collections_bill', as: "sales_collections_bills"
    #get 'collections_bill/:sale_id' => 'collections_bills#index', as: "collections_bills_index"
    post 'collections_bill' => 'collections_bills#new', as: "new_bill"

    post '/greenhouses/collections_bills/set_bol_date' => 'collections_bills#set_revised_on'
    post '/greenhouses/collections_bills/set_proforma_invoice' => 'collections_bills#set_proforma_invoice'
    get '/greenhouses/:greenhouse_id/sales/:sale_id/collections_bill/:id/adjust' => 'collections_bills#adjust', as: :adjust_collections_bill


    patch '/collections_bill/:id/save_adjustments' => 'collections_bills#save_adjustment', as: :save_adjustment





    get 'order' => 'greenhouses#order'
    get 'greenhouse/:greenhouse_id/customer/:customer_id/sales/:sale_id/invoice/:id' => 'greenhouses#invoice', as: "billing_invoice"
    get 'purshase_order/greenhouses/:greenhouse_id/sales/:sale_id' => 'greenhouses#purshase_order', as: "p_order"
    #get 'purshase_order/sales/:sale_id' => 'greenhouses#purshase_order', as: "p_order"
    get 'customs_invoice/sales/:sale_id' => 'greenhouses#customs_invoice', as: "cust_inv_pdf"
    get 'customs_invoice/manifests/:sale_id' => 'greenhouses#customs_invoice', as: 'customs_invoice'

    get 'activities' => 'static_pages#activities'


  end #Admin scope

end

app/controllers/count_types_controller.rb
class CountTypesController < ApplicationController
  before_action :set_count_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :verify_is_admin?, :except => [:get_product_count_types]

  # GET /count_types
  # GET /count_types.json
  def index
    @count_types = CountType.all
  end

  # GET /count_types/1
  # GET /count_types/1.json
  def show
  end

  # GET /count_types/new
  def new
    @count_type = CountType.new
  end

  # GET /count_types/1/edit
  def edit
  end

  # POST /count_types
  # POST /count_types.json
  def create
    @count_type = CountType.new(count_type_params)

    respond_to do |format|
      if @count_type.save
        format.html { redirect_to @count_type, notice: 'Count type was successfully created.' }
        #format.json { render :show, status: :created, location: @count_type }
      else
        format.html { render :new }
        #format.json { render json: @count_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /count_types/1
  # PATCH/PUT /count_types/1.json
  def update
    respond_to do |format|
      if @count_type.update(count_type_params)
        format.html { redirect_to @count_type, notice: 'Count type was successfully updated.' }
        #format.json { render :show, status: :ok, location: @count_type }
      else
        format.html { render :edit }
        #format.json { render json: @count_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /count_types/1
  # DELETE /count_types/1.json
  def destroy
    @count_type.destroy
    respond_to do |format|
      format.html { redirect_to count_types_url, notice: 'Count type was successfully destroyed.' }
      #format.json { head :no_content }
    end
  end

  #Esta se llama desde _shipment_fields.html.erb
  #para cargar los tipos de conteo adecuados por cada producto.
  def get_product_count_types
    types = CountType.where(product_id: params[:product_id]).order("name ASC").map { |type| [type.id, type.name] }
    render :json => types.to_json.to_s.to_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_count_type
      @count_type = CountType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def count_type_params
      params.require(:count_type).permit(:id, :name, :product_id, :_destroy)
    end

protected
    def verify_is_admin?
        (current_user.nil?) ? redirect_to(root_path) : (redirect_to(admin_path) unless current_user.admin?)
    end

end

app/helpers/count_types_helper.rb
module CountTypesHelper
end

app/views/count_types/_form.html.erb
<%= form_for(@count_type) do |f| %>
  <% if @count_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@count_type.errors.count, "error") %> prohibited this count_type from being saved:</h2>

      <ul>
      <% @count_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, Product.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/count_types/edit.html.erb
<h1>Editing Count Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @count_type %> |
<%= link_to 'Back', count_types_path %>

app/views/count_types/index.html.erb
 

<h1>Listing Count Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @count_types.each do |count_type| %>
      <tr>
        <td><%= count_type.name %></td>
        <td><%= Product.find(count_type.product_id).name  %></td>
        <td><%= link_to 'Show', count_type %></td>
        <td><%= link_to 'Edit', edit_count_type_path(count_type) %></td>
        <td><%= link_to 'Destroy', count_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Count type', new_count_type_path %>

app/views/count_types/new.html.erb
<h1>New Count Type</h1>

<%= render 'form' %>

<%= link_to 'Back', count_types_path %>

app/views/count_types/show.html.erb
 

<p>
  <strong>Name:</strong>
  <%= @count_type.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= Product.find(@count_type.product_id).name %>
</p>

<%= link_to 'Edit', edit_count_type_path(@count_type) %> |
<%= link_to 'Back', count_types_path %>