config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"
  get 'admin', to: "static_pages#admin"

  scope :admin  do

    devise_for :users
    resources :users
    resources :roles

    resources :box_types
    resources :bag_types
    resources :pallet_types
    resources :package_types
    resources :count_types
    resources :delivery_places

    resources :greenhouses do
        get 'info' => 'greenhouses#info', as: 'info'
        get 'average-prices' => 'greenhouses#average_price_week', as: "average_price_week"
        resources :sales, except: :index do
          resources :manifests
          resources :collections_bills
        end
        resources :shipments
        resources :customers do
          resources :contacts
        end
        resources :products
        resources :colors
        resources :warehouses
        resources :custom_brokers

    end


    #Hash key => value
    #what the client see => what the system does, as: alias you can use in the system


   #Estas siguientes direcciones de PATCH se requieren para que se puedan actualizar
   #los modelos anidados
   patch '/greenhouses/:greenhouse_id/customers.:id' => 'customers#update'
   patch '/greenhouses/:greenhouse_id/products.:id' => 'products#update'
   patch '/greenhouses/:greenhouse_id/sales.:id' => 'sales#update'
   patch '/greenhouses/:greenhouse_id/colors.:id' => 'colors#update'
   patch '/greenhouses/:greenhouse_id/warehouses.:id' => 'warehouses#update'
   patch '/greenhouses/:greenhouse_id/sales/:sale_id/manifests.:id' => 'manifests#update'
   patch '/greenhouses/:greenhouse_id/custom_brokers.:id' => 'custom_brokers#update'
   patch '/greenhouses/:greenhouse_id/sales/:sale_id/collections_bills.:id' => 'collections_bills#update'


#Acción al cambiar de estados en la venta
    #get 'purshase_order_state_change' => 'sales#purshase_order_state_change', as: => :purshase_order_state_change
    get 'purshase_order_state_change', action: :purshase_order_state_change, controller: 'sales'
#Fin###########


#Acción al actualizar las anotaciones en el preview de la orden de compra. order.html.erbta
    post 'annotations_update' => 'sales#annotations_update'
#Fin###########

    #Acción que se manda a llamar para cargar los conteos adecuados para cada producto.
    get 'get_product_count_types' => 'count_types#get_product_count_types'
    #Fin de esta petición ajax que se llama desde _shipment_fields.html.erb

    #Acción que se manda a ejecutar la validación apropiada.
    get '/greenhouses/sales/is_unique' => 'sales#is_unique'
    post '/greenhouses/manifests/is_unique' => 'manifests#is_unique'
    #Fin de esta petición ajax que se llama desde sales/_form.html.erb

    # Ajax Request from customs_invoice preview
    post '/greenhouses/manifests/set_leyend' => 'manifests#set_leyend'

    post 'purshase_order/greenhouses/:greenhouse_id/sales/:sale_id' => 'sales#purshase_order', as: "purshase_order"
    get 'customs_billing/sales/:greenhouse_id/:sale_id' => 'sales#customs_bill', as: "customs_billing"
    get 'customs_bill/greenhouses/:greenhouse_id/sales/:sale_id' => 'manifests#new', as: 'customs'

    get 'manifests/customs_invoice' => 'manifests#to_customs_invoice', as: "to_customs_invoice"
    get 'collections_bills/invoice/:id' => 'collections_bills#to_invoice', as: "to_invoice"

    get 'collections_bill' => 'sales#collections_bill', as: "sales_collections_bills"
    #get 'collections_bill/:sale_id' => 'collections_bills#index', as: "collections_bills_index"
    post 'collections_bill' => 'collections_bills#new', as: "new_bill"

    post '/greenhouses/collections_bills/set_bol_date' => 'collections_bills#set_revised_on'
    post '/greenhouses/collections_bills/set_proforma_invoice' => 'collections_bills#set_proforma_invoice'
    get '/greenhouses/:greenhouse_id/sales/:sale_id/collections_bill/:id/adjust' => 'collections_bills#adjust', as: :adjust_collections_bill


    patch '/collections_bill/:id/save_adjustments' => 'collections_bills#save_adjustment', as: :save_adjustment





    get 'order' => 'greenhouses#order'
    get 'greenhouse/:greenhouse_id/customer/:customer_id/sales/:sale_id/invoice/:id' => 'greenhouses#invoice', as: "billing_invoice"
    get 'purshase_order/greenhouses/:greenhouse_id/sales/:sale_id' => 'greenhouses#purshase_order', as: "p_order"
    #get 'purshase_order/sales/:sale_id' => 'greenhouses#purshase_order', as: "p_order"
    get 'customs_invoice/sales/:sale_id' => 'greenhouses#customs_invoice', as: "cust_inv_pdf"
    get 'customs_invoice/manifests/:sale_id' => 'greenhouses#customs_invoice', as: 'customs_invoice'

    get 'activities' => 'static_pages#activities'


  end #Admin scope

end

app/models/color.rb
# == Schema Information
#
# Table name: colors
#
#  id            :integer          not null, primary key
#  name          :string
#  greenhouse_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  deleted_at    :datetime
#

class Color < ActiveRecord::Base
  belongs_to :greenhouse
  acts_as_paranoid                  #Soft-Delete
  validates :greenhouse_id, presence: true
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /colors
  # GET /colors.json
  def index
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
    @colors = Color.where(greenhouse_id: @greenhouse.id)
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
  end

  # GET /colors/new
  def new
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
    @color = Color.new(greenhouse_id: @greenhouse.id)
  end

  # GET /colors/1/edit
  def edit
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
  end

  # POST /colors
  # POST /colors.json
  def create
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to greenhouse_colors_path(@greenhouse.id), notice: 'Color was successfully created.' }
        #format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        #format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1
  # PATCH/PUT /colors/1.json
  def update
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to greenhouse_color_path(@greenhouse.id, @color.id), notice: 'Color was successfully updated.' }
        #format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        #format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
    @color.destroy
    respond_to do |format|
      format.html { redirect_to greenhouse_colors_path(@greenhouse.id), notice: 'Color was successfully destroyed.' }
      #format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:id, :name, :greenhouse_id, :_destroy)
    end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_form.html.erb
<%= form_for @color, url: greenhouse_colors_path(@greenhouse.id, @color), :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.hidden_field :greenhouse_id %>

  <% if @color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% @color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-4 col-md-offset-4 col-sm-12">
    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, :required => true, class: "form-control" %>
    </div>
    <div class="row pull-right">
      <%= f.submit class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1>Editing Color</h1>

<%= render 'form' %>

<%= link_to 'Show', greenhouse_color_path(@greenhouse.id, @color.id) %> |
<%= link_to 'Back', greenhouse_colors_path(@greenhouse.id) %>

app/views/colors/index.html.erb
<div class="page-header">
  <h1>
    Colors -
    <%= "#{@greenhouse.business_name.capitalize}" %>
  </h1>
</div>

<%= render :partial => "greenhouses/submenu", :locals => {:id => @greenhouse.id } %>

<div class="well">
  <%= link_to 'Back', greenhouse_path(@greenhouse.id), class: "btn btn-default" %>
  <%= link_to 'New Color', new_greenhouse_color_path, class: "pull-right btn btn-success" %>
</div>

<div class="panel panel-default">
    <div class="panel-body">
    <table class="table table-condensed table-hover"  data-toggle="table" data-pagination="true" data-search="true">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @colors.each do |color| %>
            <tr>
                <td>
                  <%= link_to greenhouse_color_path(@greenhouse.id, color.id) do %>
                    <%= color.name %>
                  <% end %>
                </td>
                <td>
                  <%= link_to greenhouse_color_path(@greenhouse.id, color.id),
                        method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"  do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/colors/new.html.erb
<div class="well">
  <%= link_to 'Back', greenhouse_colors_path(@greenhouse.id), class: "btn btn-default" %>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">New Color</h3>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
</div>

app/views/colors/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @color.name %>
</p>

<%= link_to 'Edit', edit_greenhouse_color_path(@greenhouse.id, @color.id) %> |
<%= link_to 'Back', greenhouse_colors_path(@greenhouse.id) %>