config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"
  get 'admin', to: "static_pages#admin"

  scope :admin  do

    devise_for :users
    resources :users
    resources :roles

    resources :box_types
    resources :bag_types
    resources :pallet_types
    resources :package_types
    resources :count_types
    resources :delivery_places

    resources :greenhouses do
        get 'info' => 'greenhouses#info', as: 'info'
        get 'average-prices' => 'greenhouses#average_price_week', as: "average_price_week"
        resources :sales, except: :index do
          resources :manifests
          resources :collections_bills
        end
        resources :shipments
        resources :customers do
          resources :contacts
        end
        resources :products
        resources :colors
        resources :warehouses
        resources :custom_brokers

    end


    #Hash key => value
    #what the client see => what the system does, as: alias you can use in the system


   #Estas siguientes direcciones de PATCH se requieren para que se puedan actualizar
   #los modelos anidados
   patch '/greenhouses/:greenhouse_id/customers.:id' => 'customers#update'
   patch '/greenhouses/:greenhouse_id/products.:id' => 'products#update'
   patch '/greenhouses/:greenhouse_id/sales.:id' => 'sales#update'
   patch '/greenhouses/:greenhouse_id/colors.:id' => 'colors#update'
   patch '/greenhouses/:greenhouse_id/warehouses.:id' => 'warehouses#update'
   patch '/greenhouses/:greenhouse_id/sales/:sale_id/manifests.:id' => 'manifests#update'
   patch '/greenhouses/:greenhouse_id/custom_brokers.:id' => 'custom_brokers#update'
   patch '/greenhouses/:greenhouse_id/sales/:sale_id/collections_bills.:id' => 'collections_bills#update'


#Acción al cambiar de estados en la venta
    #get 'purshase_order_state_change' => 'sales#purshase_order_state_change', as: => :purshase_order_state_change
    get 'purshase_order_state_change', action: :purshase_order_state_change, controller: 'sales'
#Fin###########


#Acción al actualizar las anotaciones en el preview de la orden de compra. order.html.erbta
    post 'annotations_update' => 'sales#annotations_update'
#Fin###########

    #Acción que se manda a llamar para cargar los conteos adecuados para cada producto.
    get 'get_product_count_types' => 'count_types#get_product_count_types'
    #Fin de esta petición ajax que se llama desde _shipment_fields.html.erb

    #Acción que se manda a ejecutar la validación apropiada.
    get '/greenhouses/sales/is_unique' => 'sales#is_unique'
    post '/greenhouses/manifests/is_unique' => 'manifests#is_unique'
    #Fin de esta petición ajax que se llama desde sales/_form.html.erb

    # Ajax Request from customs_invoice preview
    post '/greenhouses/manifests/set_leyend' => 'manifests#set_leyend'

    post 'purshase_order/greenhouses/:greenhouse_id/sales/:sale_id' => 'sales#purshase_order', as: "purshase_order"
    get 'customs_billing/sales/:greenhouse_id/:sale_id' => 'sales#customs_bill', as: "customs_billing"
    get 'customs_bill/greenhouses/:greenhouse_id/sales/:sale_id' => 'manifests#new', as: 'customs'

    get 'manifests/customs_invoice' => 'manifests#to_customs_invoice', as: "to_customs_invoice"
    get 'collections_bills/invoice/:id' => 'collections_bills#to_invoice', as: "to_invoice"

    get 'collections_bill' => 'sales#collections_bill', as: "sales_collections_bills"
    #get 'collections_bill/:sale_id' => 'collections_bills#index', as: "collections_bills_index"
    post 'collections_bill' => 'collections_bills#new', as: "new_bill"

    post '/greenhouses/collections_bills/set_bol_date' => 'collections_bills#set_revised_on'
    post '/greenhouses/collections_bills/set_proforma_invoice' => 'collections_bills#set_proforma_invoice'
    get '/greenhouses/:greenhouse_id/sales/:sale_id/collections_bill/:id/adjust' => 'collections_bills#adjust', as: :adjust_collections_bill


    patch '/collections_bill/:id/save_adjustments' => 'collections_bills#save_adjustment', as: :save_adjustment





    get 'order' => 'greenhouses#order'
    get 'greenhouse/:greenhouse_id/customer/:customer_id/sales/:sale_id/invoice/:id' => 'greenhouses#invoice', as: "billing_invoice"
    get 'purshase_order/greenhouses/:greenhouse_id/sales/:sale_id' => 'greenhouses#purshase_order', as: "p_order"
    #get 'purshase_order/sales/:sale_id' => 'greenhouses#purshase_order', as: "p_order"
    get 'customs_invoice/sales/:sale_id' => 'greenhouses#customs_invoice', as: "cust_inv_pdf"
    get 'customs_invoice/manifests/:sale_id' => 'greenhouses#customs_invoice', as: 'customs_invoice'

    get 'activities' => 'static_pages#activities'


  end #Admin scope

end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id                   :integer          not null, primary key
#  season               :string
#  departure_date       :date
#  arrival_date         :date
#  annotation           :text
#  comment              :text
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  deleted_at           :datetime
#  user_id              :integer
#  aasm_state           :string
#  revision             :boolean          default(FALSE)
#  greenhouse_id        :integer
#  purshase_order       :boolean          default(FALSE)
#  out_of_packaging     :boolean          default(FALSE)
#  docs_reception       :boolean          default(FALSE)
#  loading_docs         :boolean          default(FALSE)
#  arrived_to_border    :boolean          default(FALSE)
#  out_of_courtyard     :boolean          default(FALSE)
#  documents            :boolean          default(FALSE)
#  mex_customs_mod      :boolean          default(FALSE)
#  us_customs_mod       :boolean          default(FALSE)
#  usda                 :boolean          default(FALSE)
#  ramp                 :boolean          default(FALSE)
#  fda                  :boolean          default(FALSE)
#  hold                 :boolean          default(FALSE)
#  arrived_to_warehouse :boolean          default(FALSE)
#  picked_up_by_cust    :boolean          default(FALSE)
#  bol                  :boolean          default(FALSE)
#  hld_qty              :integer          default(0)
#  product_color        :string
#  ship_number          :string
#  delivery_place_id    :integer
#  warehouse_id         :integer
#



# 1)  Orden de compra
# 2)  Recepcion de documentos
# 3)  Salio de empaque
# 4)  Documentacion de carga
# 5)  Llego a frontera
# 6)  Salio del patio
# 7)  Cuenta con documentos
# 8)  Modulo aduana Mexicana
# 9)  Rojo al pasar ?
# 10) Modulo aduana Americana
# 11) FDA
# 12) USDA
# 13) Rampa
# 14) Rayos
# 15) Llego a bodega
# 16) Recogio el cliente
# 17) BOL

class Sale < ActiveRecord::Base
  include AASM
  #Documentación https://github.com/rubyist/aasm

  acts_as_paranoid

  belongs_to :greenhouse
  belongs_to :user
  has_many :shipments, :dependent => :destroy, :source_type => "Shipment"
  has_many :customers, :through => :shipments
  has_one :manifest
  has_many :shipment_state_changes
  has_many :collection_bills, inverse_of: :sale

  accepts_nested_attributes_for :shipments,  :allow_destroy => true,
  reject_if: proc { |attributes| attributes['price'].blank? ||
   attributes['box_number'].blank? || attributes['package_type_id'].blank? ||
   attributes['pallet_type_id'].blank? || attributes['box_type_id'].blank? ||
   attributes['bag_type_id'].blank? }

  accepts_nested_attributes_for :customers, :reject_if => :all_blank
  accepts_nested_attributes_for :manifest, :allow_destroy => true

  def own? user
    self.user_id == user.id
  end

  filterrific(
  default_filter_params: { sorted_by: 'created_at_desc' },
  available_filters: [
    :sorted_by,
    :with_ship_number,
    :with_customer_id,
    :with_created_at_after,
    :with_created_at_before
     ]
  )


  scope :with_ship_number, lambda { |ship_number|

    where("ship_number LIKE ?", "%#{ship_number}%")
    # if(ship_number[:value].empty?)
    #   where("greenhouse_id = ?", ship_number[:greenhouse_id]) if ship_number.greenhouse_id.present?
    # else
    #   where("ship_number LIKE ? AND greenhouse_id = ?", "%#{ship_number[:value].downcase.to_i}%", ship_number[:greenhouse_id]) if ship_number.greenhouse_id.present?
    # end
   }

  scope :with_customer_id, lambda { |customer_ids|
    Sale.includes(:shipments).where( :shipments => { :customer_id => [*customer_ids] })
  }

  scope :with_created_at_after, lambda { |ref_date|
    where('sales.departure_date >= ?', ref_date)
  }

  scope :with_created_at_before, lambda { |ref_date|
    where('sales.departure_date <= ?', ref_date)
  }

    scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^departure_date_/
      order("sales.departure_date #{ direction }")
    when /^ship_num_/
      order("LOWER(ship_number) #{ direction }")
    when /^customer_/
      order("LOWER(customers.business_name) #{ direction }").includes(:customers).references(:shipments)
    when /^created_at_/
      order("sales.created_at #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }


  def self.options_for_sorted_by
    [
      ['Shipment # (a-z)', 'ship_num_asc'],
       ['Shipment # (z-a)', 'ship_num_desc'],
      ['Departure date (newest first)', 'departure_date_desc'],
      ['Departure date (oldest first)', 'departure_date_asc'],
      ['Customer (a-z)', 'customer_asc'],
      ['Customer (z-a)', 'customer_desc']
    ]
  end



  scope :total_month_sales_ammount, -> { select("SUM(shipments.price * shipments.box_number) AS TOTAL_AMMOUNT")
    .joins(:shipments).where("EXTRACT(MONTH FROM sales.created_at) = ?", Time.now.month) }

  #$states_to_s = {:carrier_courtyard_checkin => {:id => "1", :name => "Carrier Courtyard Arrival"},
  #               :courtyard_to_modules_line => {:id => "2", :name => "In course to Modules Line"},
  #              :mexican_modules => {:id => "3", :name => "Mexican Modules"},
  #             :american_modules => {:id => "4", :name => "American Modules"},
  #            :fda_inspection => {:id => "5", :name => "FDA Inspection"},
  #           :to_warehouse => {:id => "6", :name => "To Warehowse"},
  #          :delivered => {:id => "7", :name => "Delivered"},
  #          :payed => {:id => "8", :name => "Payed"}
  #       }


  # Public Activity
  include PublicActivity::Model
  tracked owner:  ->(controller, model) { controller.c_user }

  #Se definen los estados que se desea estén como parte del proceso de operaciones de la empresa
  #Vanguard.
  #
  $states = {:none => {:id => "0", :name => "Inicial"},
    :purshase_order => {:id => "1", :name => "Orden de Compra"},
    :out_of_packaging => {:id => "2", :name => "Salió de empaque"},
    :docs_reception => {:id => "3", :name => "Recepción de Documentos"},
    :loading_docs => {:id => "4", :name => "Documentación de carga"},
    :arrived_to_border => {:id => "5", :name => "Legó a Frontera"},
    :out_of_courtyard => {:id => "6", :name => "Salió de Patio"},
    :documents => {:id => "7", :name => "Cuenta con documentos"},
    :mex_customs_mod => {:id => "8", :name => "Modulo Aduana Mexicana"},
    :us_customs_mod => {:id => "9", :name => "Modulo Aduana Americana"},
    :arrived_to_warehouse => {:id => "10", :name => "Legó a Bodega"},
    :picked_up_by_cust => {:id => "11", :name => "Recogió el cliente"},
    :bol => {:id => "12", :name => "BOL"},
    :revision => {:id => "13", :name => "Revisión en Rojo"},
    :usda => {:id => "14", :name => "USDA"},
    :fda => {:id => "15", :name => "FDA"},
    :ramp => {:id => "16", :name => "Rampa"},
    :hld_qty => {:id => "17", :name => "QTY"},
    :rays_scan => {:id => "18", :name => "Rayos"}
  }

  def completed_states_size
    ($states_to_s[self.aasm_state.to_sym][:id].to_f-1)/8*100
  end

  def actual_state_size
    return (100.0/12.0).to_f
  end

  def pending_states_size
    #Reemplazar el 12 por cada uno de los eventos
    (12.0 - $states_to_s[self.aasm_state.to_sym][:id].to_f)/12*100
  end

  def total_pallets
    self.shipments.map { |r|  r[:pallets_number] }.sum
  end

  aasm do # default column: aasm_state

    #Los siguientes son los estados de la máquina de estados.
    # El estado inicial.
    state :none, :initial => true
    state :purshase_order
    state :out_of_packaging
    state :docs_reception
    state :loading_docs
    state :arrived_to_border
    state :out_of_courtyard
    state :documents
    state :mex_customs_mod
    state :us_customs_mod
    state :arrived_to_warehouse
    state :picked_up_by_cust
    state :bol
    state :revision
    state :usda
    state :fda
    state :ramp
    #Se pidió unir la propiedad hold + fda. Solo dejamos fda.
    #state :hold
    state :hld_qty
    state :rays_scan



    #Eventos y trancisiones.
    event :primera do
      transitions :from => [:none, :purshase_order, :out_of_packaging, :docs_reception,
        :loading_docs, :arrived_to_border, :out_of_courtyard, :documents,
        :mex_customs_mod, :us_customs_mod, :arrived_to_warehouse, :picked_up_by_cust,
      :bol, :revision, :usda, :fda, :ramp, :hld_qty, :rays_scan],
      :to => :purshase_order, :after => Proc.new {|user| log_change(user)}
      #Aquí se pueden poner todas las conduciones especificadas en la documentación
      #:after => :state_appropiate?, :guard => :already_sold?
    end

    event :segunda do

      transitions :from => [:none, :purshase_order, :out_of_packaging, :docs_reception,
        :loading_docs, :arrived_to_border, :out_of_courtyard, :documents,
        :mex_customs_mod, :us_customs_mod, :arrived_to_warehouse, :picked_up_by_cust,
      :bol, :revision, :usda, :fda, :ramp, :hld_qty, :rays_scan],
      :to => :out_of_packaging, :after => Proc.new {|user| log_change(user)}
      #Aquí se pueden poner todas las conduciones especificadas en la documentación
      #:after => :state_appropiate?, :guard => :already_sold?
    end

    event :tercera do

      transitions :from => [:none, :purshase_order, :out_of_packaging, :docs_reception,
        :loading_docs, :arrived_to_border, :out_of_courtyard, :documents,
        :mex_customs_mod, :us_customs_mod, :arrived_to_warehouse, :picked_up_by_cust,
      :bol, :revision, :usda, :fda, :ramp, :hld_qty, :rays_scan],
      :to => :docs_reception, :after => Proc.new {|user| log_change(user)}
      #Aquí se pueden poner todas las conduciones especificadas en la documentación
      #:after => :state_appropiate?, :guard => :already_sold?
    end

    event :cuarta do

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/DEPRECATED_preshipments_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <% if @action != "edit" %>
      <th>Use</th>
      <% end %>
      <th>ID</th>
      <th>Product Name</th>
      <th>Price</th>
      <th>Start At</th>
      <th>Created At</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shipments.each do |shipment| %>
      <tr>
        <% if @action != "edit" %>
         <td><%= check_box_tag "shipment_ids[]", shipment.id %></td>
        <% end %>
        <td><%= shipment.id %></td>
        <td><%= shipment.product.name %></td>

        <% if @action != "edit" %>
        <td>$<%= number_field_tag shipment.id, nil, min: 0, max: 100000, step: :any  %></td>
        <% else %>
         <td>$<%= number_field_tag shipment.id, shipment.price,  min: 0, max: 100000, step: :any %></td>
        <% end %>





        <td><%=l shipment.start_at, format: :long  %></td>
        <td><%=l shipment.created_at, format: :long %></td>

        <td>
          <%= link_to shipment_path(shipment), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <i class="fa fa-info fw"></i>
          <%- end -%>
          <%= link_to edit_shipment_path(shipment), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <i class="fa fa-pencil fw"></i>
          <%- end -%>
          <%= link_to shipment_path(shipment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <i class="fa fa-trash-o fw"></i>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/_customer_fields.html.erb
<div id="products" class="panel  panel-default">
    <div class="form-group">
      <%= f.label :customer, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= collection_select :shipment, :customer_id, Customer.all, :id, :business_name, prompt: "Selecciona cliente",:class => 'text_field form-control' %>
    </div>
  </div>

    <div class="panel-heading">
      <h3>Products</h3>
    </div>
    <div class="panel-body">
      <%= f.fields_for :shipments do |shipment| %>
        <%= render 'shipment_fields', :f  => shipment %>
      <% end %>
      <%= link_to_add_association 'Add product', f, :shipments, render_options: { wrapper: 'inline' }, :class => "btn btn-primary btn-small" %>
    </div>
</div>

app/views/sales/_form.html.erb
<%= form_for @sale, :url => greenhouse_sales_path(@greenhouse.id, @sale.id), :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :shipment_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ship_number, :class => 'text_field form-control', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :season, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :season, :class => 'text_field form-control', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :delivery_place, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.collection_select :delivery_place_id, DeliveryPlace.all, :id, :name, class: "form-control", :required => true  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :warehouse_id, :class => 'control-label col-md-2' %>
      <div class="col-md-10">
        <%= f.collection_select :warehouse_id, @warehouses, :id, :name_address,
               {prompt: "Selecciona bodega"}, class: "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :departure_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :departure_date, :class => 'text_field form-control', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :arrival_date, :class => 'control-label col-md-2', :required => true %>
    <div class="col-md-10">
      <%= f.date_select :arrival_date, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :observations, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :annotation, :class => 'text_field form-control' %>
    </div>
  </div>

  <div id="products" class="panel  panel-default">
    <div class="panel-heading">
      <h3>Products</h3>
    </div>
    <%= hidden_field_tag(:po_number_hidden) %>
    <%= hidden_field_tag(:customer_id_hidden) %>
    <div class="panel-body" id="shipments-panel">
      <div id="shipments-list">
      <%= f.fields_for :shipments do |shipment| %>
          <%= render 'shipment_fields', :f  => shipment %>
      <% end %>
      </div>

      <%= link_to_add_association 'Add Product', f, :shipments,  data: {"association-insertion-method" => :append, "association-insertion-node" => "#shipments-list" }, :class => "btn btn-primary btn-small margin-up pull-right" %>
    </div>
  </div>


    <!-- render :partial => 'preshipments_table' %>-->
  <!--<div class="form-group">
    < f.label :comment, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      < f.text_field :comment, :class => 'text_field form-control' %>
    </div>
  </div>-->

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%if @edit %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  greenhouse_sale_path(@greenhouse.id, @sale.id), :class => 'btn btn-default' %>
      <%else%>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  greenhouse_path(@greenhouse.id), :class => 'btn btn-default' %>
      <%end%>
                  <% if @sale.own?(current_user)%>
      <%= link_to t('.delete', :default => t("helpers.links.delete")),
                  greenhouse_sales_path, :class => 'btn btn-danger' %>
                  <% end %>
    </div>
  </div>
<% end %>
<script type="text/javascript">


  //This callback is triggered after clicking in add Product, and the controls
  //gets here before showing results on the screen.
  $("#shipments-panel").on('cocoon:before-insert', function(e, inserted_item){
      //Selected by parent class and own class of input in which is
      // wanted to set the value when added.
      $(".nested-fields .po_num", inserted_item).val($('#po_number_hidden').val());

      $(".nested-fields .cust_id", inserted_item).val($('#customer_id_hidden').val());



  }).on('cocoon:before-remove', function(e, task) {
        // allow some time for the animation to complete
        $(this).data('remove-timeout', 3400);
        task.fadeOut('slow');
      });

$('#sale_ship_number').on('change', function(){

          if($('#sale_ship_number').val() != ""){

            var params = {
              ship_number: $('#sale_ship_number').val(),
              greenhouse_id: '<%= @greenhouse.id %>'
            };

            $.ajax({
            url: '<%= greenhouses_sales_is_unique_path %>',
            type: 'GET',
            data: $.param(params),
            dataType: 'json',
            success: function (dataRes) {

              if(dataRes["is_unique"] == false){

                    var ship_number = $('#sale_ship_number').val();
                    $('#sale_ship_number').val(dataRes["next_ship_number"]);
                    $("#messages").html('<div class="alert alert-error fade in">  '+
                      dataRes["error_message"]+" "+ ship_number+'<button class="close" data-dismiss="alert"> x</button></div>');
                }

              }
          });

          }

});


</script>

app/views/sales/_preshipments_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <% if @action != "edit" %>
      <th>Use</th>
      <% end %>
      <th>ID</th>
      <th>Product Name</th>
      <th>Price</th>
      <th>Start At</th>
      <th>Created At</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shipments.each do |shipment| %>
      <tr>
        <% if @action != "edit" %>
         <td><%= check_box_tag "shipment_ids[]", shipment.id %></td>
        <% end %>
        <td><%= shipment.id %></td>
        <td><%= shipment.product.name %></td>

        <% if @action != "edit" %>
        <td>$<%= number_field_tag shipment.id, nil, min: 0, max: 100000, step: :any  %></td>
        <% else %>
         <td>$<%= number_field_tag shipment.id, shipment.price,  min: 0, max: 100000, step: :any %></td>
        <% end %>





        <td><%=l shipment.start_at, format: :long  %></td>
        <td><%=l shipment.created_at, format: :long %></td>

        <td>
          <%= link_to shipment_path(shipment), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <i class="fa fa-info fw"></i>
          <%- end -%>
          <%= link_to edit_shipment_path(shipment), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <i class="fa fa-pencil fw"></i>
          <%- end -%>
          <%= link_to shipment_path(shipment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <i class="fa fa-trash-o fw"></i>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/edit.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit Shipment'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<%- model_class = Sale -%>
<ol class="breadcrumb">
  <li><%= link_to "#{@greenhouse.business_name}", greenhouse_path(@greenhouse) %></li>
  <li class="active">Sales</li>
</ol>
<div class="page-header">
  <h1>Shipments</h1>
  <div class="pull-right">
    <%= link_to t('.new', :default => t("helpers.links.new")),
                                              new_greenhouse_sale_path(@greenhouse),
                                            :class => 'btn btn-success btn-lg' %>
  </div>
</div>

<% if @sales.present? %>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <table class="table table-striped"  data-toggle="table" data-pagination="true" data-search="true">
          <thead>
            <tr>
              <th></th>
              <!--<th>< model_class.human_attribute_name(:id) %></th>-->
              <th><%= model_class.human_attribute_name(:product) %></th>
              <th><%= model_class.human_attribute_name(:customer) %></th>
              <th><%=t '.actions', :default => t("helpers.actions") %></th>
            </tr>
          </thead>
          <tbody>
            <% @sales.each do |sale| %>
            <tr data-link="<%= greenhouse_sale_path(@greenhouse.id, sale.id) %>">
                <td><%= radio_button_tag(:selected, sale.id) %></td>
                <td><%= sale.id %></td>
                <td><a href="<%= greenhouse_sale_path(@greenhouse.id, sale.id) %>">
                  <%if !sale.shipments.empty? %>
                    <%= sale.shipments.first.product.name %>
                    <%else %>
                    Detalles
                  <%end%>
                  </a></td>
                <td><a href="<%= greenhouse_sale_path(@greenhouse.id, sale.id) %>">
                  <%if !sale.shipments.empty? %>
                  <%= sale.shipments.first.customer.customers_in_sale(sale) %>
                  <%else %>
                    Detalles
                  <%end%>
                </a></td>
                <td>
                  <%= link_to edit_greenhouse_sale_path(sale.greenhouse_id, sale.id), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
                  <i class="fa fa-pencil fw"></i>
                  <%- end -%>
                </td>
            </tr>
            <% end %>
            <!-- El contenido retirado va entre los dos <tbody/>-->
          </tbody>
        </table>
      </div>
      <%= render "state_machine" %>
    </div>
  </div>
<% else %>
  <h3 class="text-muted text-center">No data.</h3>
<% end %>

app/views/sales/new.html.erb
<%- model_class = Sale -%>

<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New Shipment'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>