config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"
  get 'admin', to: "static_pages#admin"

  scope :admin  do

    devise_for :users
    resources :users
    resources :roles

    resources :box_types
    resources :bag_types
    resources :pallet_types
    resources :package_types
    resources :count_types
    resources :delivery_places

    resources :greenhouses do
        get 'info' => 'greenhouses#info', as: 'info'
        get 'average-prices' => 'greenhouses#average_price_week', as: "average_price_week"
        resources :sales, except: :index do
          resources :manifests
          resources :collections_bills
        end
        resources :shipments
        resources :customers do
          resources :contacts
        end
        resources :products
        resources :colors
        resources :warehouses
        resources :custom_brokers

    end


    #Hash key => value
    #what the client see => what the system does, as: alias you can use in the system


   #Estas siguientes direcciones de PATCH se requieren para que se puedan actualizar
   #los modelos anidados
   patch '/greenhouses/:greenhouse_id/customers.:id' => 'customers#update'
   patch '/greenhouses/:greenhouse_id/products.:id' => 'products#update'
   patch '/greenhouses/:greenhouse_id/sales.:id' => 'sales#update'
   patch '/greenhouses/:greenhouse_id/colors.:id' => 'colors#update'
   patch '/greenhouses/:greenhouse_id/warehouses.:id' => 'warehouses#update'
   patch '/greenhouses/:greenhouse_id/sales/:sale_id/manifests.:id' => 'manifests#update'
   patch '/greenhouses/:greenhouse_id/custom_brokers.:id' => 'custom_brokers#update'
   patch '/greenhouses/:greenhouse_id/sales/:sale_id/collections_bills.:id' => 'collections_bills#update'


#Acción al cambiar de estados en la venta
    #get 'purshase_order_state_change' => 'sales#purshase_order_state_change', as: => :purshase_order_state_change
    get 'purshase_order_state_change', action: :purshase_order_state_change, controller: 'sales'
#Fin###########


#Acción al actualizar las anotaciones en el preview de la orden de compra. order.html.erbta
    post 'annotations_update' => 'sales#annotations_update'
#Fin###########

    #Acción que se manda a llamar para cargar los conteos adecuados para cada producto.
    get 'get_product_count_types' => 'count_types#get_product_count_types'
    #Fin de esta petición ajax que se llama desde _shipment_fields.html.erb

    #Acción que se manda a ejecutar la validación apropiada.
    get '/greenhouses/sales/is_unique' => 'sales#is_unique'
    post '/greenhouses/manifests/is_unique' => 'manifests#is_unique'
    #Fin de esta petición ajax que se llama desde sales/_form.html.erb

    # Ajax Request from customs_invoice preview
    post '/greenhouses/manifests/set_leyend' => 'manifests#set_leyend'

    post 'purshase_order/greenhouses/:greenhouse_id/sales/:sale_id' => 'sales#purshase_order', as: "purshase_order"
    get 'customs_billing/sales/:greenhouse_id/:sale_id' => 'sales#customs_bill', as: "customs_billing"
    get 'customs_bill/greenhouses/:greenhouse_id/sales/:sale_id' => 'manifests#new', as: 'customs'

    get 'manifests/customs_invoice' => 'manifests#to_customs_invoice', as: "to_customs_invoice"
    get 'collections_bills/invoice/:id' => 'collections_bills#to_invoice', as: "to_invoice"

    get 'collections_bill' => 'sales#collections_bill', as: "sales_collections_bills"
    #get 'collections_bill/:sale_id' => 'collections_bills#index', as: "collections_bills_index"
    post 'collections_bill' => 'collections_bills#new', as: "new_bill"

    post '/greenhouses/collections_bills/set_bol_date' => 'collections_bills#set_revised_on'
    post '/greenhouses/collections_bills/set_proforma_invoice' => 'collections_bills#set_proforma_invoice'
    get '/greenhouses/:greenhouse_id/sales/:sale_id/collections_bill/:id/adjust' => 'collections_bills#adjust', as: :adjust_collections_bill


    patch '/collections_bill/:id/save_adjustments' => 'collections_bills#save_adjustment', as: :save_adjustment





    get 'order' => 'greenhouses#order'
    get 'greenhouse/:greenhouse_id/customer/:customer_id/sales/:sale_id/invoice/:id' => 'greenhouses#invoice', as: "billing_invoice"
    get 'purshase_order/greenhouses/:greenhouse_id/sales/:sale_id' => 'greenhouses#purshase_order', as: "p_order"
    #get 'purshase_order/sales/:sale_id' => 'greenhouses#purshase_order', as: "p_order"
    get 'customs_invoice/sales/:sale_id' => 'greenhouses#customs_invoice', as: "cust_inv_pdf"
    get 'customs_invoice/manifests/:sale_id' => 'greenhouses#customs_invoice', as: 'customs_invoice'

    get 'activities' => 'static_pages#activities'


  end #Admin scope

end

app/models/collections_bill.rb
# == Schema Information
#
# Table name: collections_bills
#
#  id               :integer          not null, primary key
#  sale_id          :integer
#  user_id          :integer
#  invoice_number   :integer
#  po_number        :string
#  payment_terms    :string(100)
#  bol_date         :datetime
#  total_amt        :float
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  deleted_at       :datetime
#  customer_id      :integer
#  ship_number      :string
#  proforma_invoice :string
#  show_color       :boolean          default(FALSE), not null
#  show_count_type  :boolean          default(FALSE), not null
#  show_pkg_type    :boolean          default(FALSE), not null
#  show_bag_type    :boolean          default(FALSE), not null
#  show_plu         :boolean          default(FALSE), not null
#  label_one        :string           default(""), not null
#  label_two        :string           default(""), not null
#  bill_of_lading   :string           default(""), not null
#  thermograph      :string           default(""), not null
#  footer_one       :text             default(""), not null
#  footer_two       :text             default(""), not null
#

class CollectionsBill < ActiveRecord::Base
  acts_as_paranoid           #Soft-delete

  belongs_to :user
  belongs_to :sale
  belongs_to :customer, inverse_of: :collections_bill
  has_many :shipments, :through => :customer, :dependent => :destroy, inverse_of: :collections_bill
  has_many :shipment_adjustments, through: :shipments, inverse_of: :collections_bill

  accepts_nested_attributes_for :sale
  accepts_nested_attributes_for :shipment_adjustments

  # Public Activity
  include PublicActivity::Model
  tracked owner:  ->(controller, model) { controller.c_user }

  def adjusted_shipments
    self.sale.shipments.each do |sh|
      if sh.shipment_adjustment.present?
        sh.price = sh.shipment_adjustment.price
        sh.weight = sh.shipment_adjustment.weight
        sh.box_number = sh.shipment_adjustment.box_number
      else
        return nil
      end
    end
  end

  def adjusted?
    self.shipment_adjustments.any? 
  end

  def own_shipments
    Shipment.where(:sale_id => self.sale_id, :customer_id => self.customer_id).order(id: :asc)
  end

  def total_from_adjustments
    self.shipment_adjustments.map {|r| r[:price] * r[:box_number] }.sum
  end

end

app/controllers/collections_bills_controller.rb
class CollectionsBillsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_collections_bill, only: [:show, :edit, :update,
    :destroy, :to_invoice, :adjust, :save_adjustment]



  # GET /collections_bills
  # GET /collections_bills.json
  def index
    @collections_bills = CollectionsBill.all
  end

  # GET /collections_bills/1
  # GET /collections_bills/1.json
  def show
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
    @sale = Sale.find(@collections_bill.sale_id)
    @customer = Customer.find(@collections_bill.customer_id)
    respond_to do |format|
      format.html { redirect_to to_invoice_path(@collections_bill), notice: 'Collections bill was successfully created.' }
    end
  end

#This method is called from the CollectionsBill Show view and it redirects to
#the greenhouse invoice method
  def to_invoice
    bill = CollectionsBill.find(params[:id])
    sale = Sale.find(bill.sale_id)
    greenhouse = Greenhouse.find(sale.greenhouse_id)
    customer = Customer.find(bill.customer_id)
    redirect_to billing_invoice_path(greenhouse.id, customer.id, sale.id, bill.id)
  end



  # GET /collections_bills/new
  def new

    @sale = Sale.find(params[:sale_id])
    @customer = Customer.find(params[:customer_id])
    @bill = CollectionsBill.where(:sale_id => @sale.id).where(:customer_id => @customer.id)

    if @bill.empty?


      @greenhouse = Greenhouse.find(params[:greenhouse_id])


      @manifest = Manifest.where("sale_id = ?", @sale.id).first
      @collections_bill = CollectionsBill.new(:sale_id => @sale.id, :customer_id =>
        @customer.id, :user_id => current_user.id, :ship_number => @sale.ship_number)

      #Shipments filtered by sale and customer

      set_shipments_values
      @total_ammount_money_words = @total_ammount_money.to_f.to_words.upcase + " DOLARES 00/100 USD"
      @collections_bill.payment_terms = "Net 10 day Invoce date."

      if @manifest != nil

        @collections_bill.po_number = @manifest.po_number
        @collections_bill.bill_of_lading = @manifest.po_number
        @collections_bill.ship_number = @manifest.ship_number
        @collections_bill.total_amt = @total_ammount_money
        @collections_bill.proforma_invoice = @manifest.custom_invoice_id
        #Fixed 12 is because the state "bol"
        #This following where conditions are for the last time the bol state was updated to true
        bol_event = ShipmentStateChanges.last_bol_date(@sale.id, $states[:bol][:id].to_i)

        if bol_event == nil
          @collections_bill.bol_date = @sale.arrival_date
        else
          @collections_bill.bol_date = bol_event.created_at
        end


        @collections_bill.thermograph = @manifest.thermograph
        @collections_bill.label_one = "* Product of México"
        @collections_bill.label_two = "\"Instructions for payment via wire transfer:\n #{@greenhouse.business_name}\n Frost National Bank\n Account: 010505900\n ABA: 114000093\""
        @collections_bill.footer_one = "\"This proforma invoice is used for collection purposes This invoice must be paid in full. No short payments will be accepted without a written authorization from us.\""
        @collections_bill.footer_two = "The perishable agricultural commodities listed on this invoice are sold subject to the statuory \ntrust authorized by section 5(c) of the Perishable Agricultural Commodities Act,\n 1930 (7 U.S.C. 499e(c)). The seller of these commodities retains a trust claim over these \ncommodities, all inventories of food or other products derived from these commodities, and \nany receivables or proceeds from the sale of these commodities until full payment is received.\n"


      else # del if manifest != nil
        @collections_bill.po_number = @sale.shipments.first.po_number
      end

    else # else del @bill.empty?
      return redirect_to to_invoice_path(@bill.first.id)
    end
  end

  # GET /collections_bills/1/edit
  def edit
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
    @sale = Sale.find(@collections_bill.sale_id)
    @customer = Customer.find(@collections_bill.customer_id)
    set_shipments_values
  end

  # POST /collections_bills
  # POST /collections_bills.json
  def create
    #customer_id comes from a hidden field
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
    @sale = Sale.find(params[:sale_id])


    @collections_bill = CollectionsBill.new(collections_bill_params)
    @collections_bill.user_id = current_user.id
    respond_to do |format|
      if @collections_bill.save
        #format.html { redirect_to greenhouse_sale_collections_bill_path(@greenhouse.id, @sale.id, @collections_bill.id), notice: 'Collections bill was successfully created.' }
        format.html { redirect_to to_invoice_path(@collections_bill), notice: 'Collections bill was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /collections_bills/1
  # PATCH/PUT /collections_bills/1.json
  def update
    respond_to do |format|
      if @collections_bill.update(collections_bill_params)
        format.html { redirect_to to_invoice_path(@collections_bill), notice: 'Collections bill was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /collections_bills/1
  # DELETE /collections_bills/1.json
  def destroy
    @collections_bill.destroy
    respond_to do |format|
      format.html { redirect_to collections_bills_url, notice: 'Collections bill was successfully destroyed.' }
    end
  end

  def revised_on
    collections_bill = CollectionsBill.find(params[:collections_bill_id])
    collections_bill.bol_date = DateTime.parse(params[:bol_date])

    result = {}

    if collections_bill.save

        result = {
                  :success => true,
                  :error_message => "",
                  :message => "·Updated·"}
    else

        result = {
                  :success => false,
                  :error_message => "Internal error while update.",
                  :message => "·Error·"}
    end

    render :json => result
  end

  def set_revised_on
    collections_bill = CollectionsBill.find(params[:collections_bill_id])
    collections_bill.bol_date = DateTime.parse(params[:bol_date])

    result = {}

    if collections_bill.save

        result = {:success => true,
                  :message => "·Updated·"}
    else
        result = {:error_message => "Internal error while update."}
    end

    render :json => result
  end



def set_proforma_invoice
    collections_bill = CollectionsBill.find(params[:collections_bill_id])
    collections_bill.proforma_invoice = params[:proforma_invoice]
    result = {}
    if collections_bill.save
        result = {
                  :success => true,
                  :message => "·Updated·"}
    else
        result = {:error_message => "Internal error while update."}
    end
    render :json => result
  end

  def adjust
    @greenhouse = Greenhouse.find(params[:greenhouse_id])
    @sale = Sale.find(@collections_bill.sale_id)
    @customer = Customer.find(@collections_bill.customer_id)
    set_shipments_values
    # if @collections_bill.adjusted?
    #     respond_to do |format|
    #       format.html { redirect_to to_invoice_path(@collections_bill), notice: 'Collections bill was successfully created.' }
    #   end
    # else
      respond_to do |format|
        format.html { render :adjust }
      end
    #end
  end

  def save_adjustment
    if save_adjusments

      redirect_to to_invoice_path(@collections_bill, :show_adjusted => "true"), notice: 'Collections bill was successfully created.' 

    else
      respond_to do |format|
        format.html { render :adjust }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_collections_bill
    @collections_bill = CollectionsBill.find(params[:id])
  end

  def set_shipments_values
      @shipments = Shipment.where("sale_id = ? AND  customer_id = ?", @sale.id, @customer.id ).order(id: :asc)
      @total_boxes =  @shipments.map { |r| r[:box_number] }.sum
      @total_weight =  @shipments.map { |r| r[:weight] }.sum
      @total_ammount_money =  @shipments.map { |r| r[:price] * r[:box_number] }.sum
  end

  def save_adjusments
    success = false
    shipment_adjustment_attributes = adjustments_params[:shipment_adjustments_attributes]
    shipment_adjustment_attributes.each do |adjustment|
      if adjustment.last[:id].present?
        shipment_adjustment = ShipmentAdjustment.find(adjustment.last[:id])
        shipment_adjustment.update(adjustment.last) ? success = true : success = false
      else
        shipment_adjustment = ShipmentAdjustment.new(adjustment.last)
        shipment_adjustment.save ? success = true : success = false
      end

    end
  end

  def adjustments_params
    params.require(:collections_bill).permit(:user_id, :customer_id, :sale_id, :shipment_adjustments_attributes => [:id, :shipment_id, :box_number, :price, :weight ] )
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def collections_bill_params
    params.require(:collections_bill).permit(:id, :sale_id, :invoice_number,
      :ship_number, :po_number, :payment_terms, :bol_date, :total_amt,
      :user_id, :customer_id, :created_at, :label_one, :label_two, :bill_of_lading,
      :proforma_invoice, :show_pkg_type, :show_plu, :show_count_type, :show_color,
      :show_bag_type, :thermograph, :footer_one, :footer_two, :_destroy,
      sale_attributes:[shipments_attributes: [:id, :product_id, :start_at, :pallets_number,
      :comments, :sale_id, :price, :plu, :count, :product_color, :_destroy,
      shipment_adjustment_attributes: [:box_number, :price, :weight]]]
      )
  end

end

app/helpers/collections_bills_helper.rb
module CollectionsBillsHelper
end

app/views/collections_bills/_adjust_form.html.erb
<%= form_for @collections_bill, :url =>  save_adjustment_path(@collections_bill.id) do |cb_form| %>
   <%= cb_form.hidden_field(:user_id, :value => @collections_bill.user_id) %>
   <%= cb_form.hidden_field(:customer_id, :value => @collections_bill.customer_id) %>
   <%= cb_form.hidden_field(:sale_id, :value => @sale.id) %>

  <% if @collections_bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collections_bill.errors.count, "error") %> prohibited this collections_bill from being saved:</h2>

      <ul>
      <% @collections_bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="panel panel-default">
  <div class="panel-heading">Details</div>
    <div class="panel-body">
          <div class="row">
            <div id="confirmed-table" class="col-md-12 col-xs-12">
              <%= render :partial => 'collections_bills/adjust_confirmed_sales',  :locals => {:f => cb_form, :bill => @collections_bill }  %>
            </div>
          </div>
      <div class="row">
        <div class="col-md-4">
          <%= cb_form.label :proforma_invoice, class: "control-label" %>
          <%= cb_form.text_field :proforma_invoice, :disabled => true, class: "form-control" %>
        </div>
        <div class="col-md-4">
          <%= cb_form.label "Shipment # ", class: "control-label" %>
          <%= cb_form.text_field :ship_number, :disabled => true, class: "form-control" %>
        </div>
        <div class="col-md-4">
          <%= cb_form.label "Purshase order #", class: "control-label" %>
          <%= cb_form.text_field :po_number, :disabled => true, class: "form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <%= cb_form.label :payment_terms, class: "control-label" %>
          <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" title="Max 100 characters"></span>
          <%= cb_form.text_area :payment_terms, class: "form-control", :disabled => true,
          :maxlength => 100, :onkeyup => "check_max_length(this);", cols: 20, rows: 1 %>
        </div>
        <div class="row">
        <div class="col-md-6">
            <%= cb_form.label :bol_date, class: "control-label" %>
          </div>
          <div class="col-md-6">
            <%= cb_form.datetime_select :bol_date, :disabled => true, class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="col-md-12">
            <%= cb_form.label "Total ammount", class: "control-label" %>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= cb_form.text_field :total_amt, :disabled => true, class: "form-control" %>
            </div>
            <div class="col-md-6">
              <%= @total_ammount_money_words %>
            </div>
          </div>
      </div>
      <div class="row">
        <div class="col-md-6">
            <div class="col-md-6 col-xs-12">
              <%= cb_form.label :bill_of_lading, class: "control-label" %>
              <%= cb_form.text_field :bill_of_lading, :disabled => true, class: "form-control" %>
            </div>
            <div class="col-md-6 col-xs-12">
              <%= cb_form.label :thermograph, class: "control-label" %>
              <%= cb_form.text_field :thermograph, :disabled => true, class: "form-control" %>
            </div>
        </div>
      </div>
    </div>


        <div class="row detail-switches">
          <div class="col-md-12 col-md-offset-1">
            <p>Show Details:</p>
            <div class="form-group col-sm-4 col-md-2">
              <%= cb_form.label "Bag Type", class: "control-label col-md-12" %>
              <div class="col-md-6">
                <%= cb_form.check_box :show_bag_type, {:disabled => true, class: "col-md-6"} %>
              </div>
            </div>
            <div class="form-group col-sm-4 col-md-2">
              <%= cb_form.label "Package Type", class: "control-label col-md-12" %>
              <div class="col-md-6">
                <%= cb_form.check_box  :show_pkg_type, { :disabled => true, class: "col-md-6"} %>
              </div>
            </div>
            <div class="form-group col-sm-4 col-md-2">
              <%= cb_form.label "Count Type", class: "control-label col-md-12" %>
              <div class="col-md-6">
                <%= cb_form.check_box  :show_count_type, { :disabled => true, class: "col-md-6"} %>
              </div>
            </div>
            <div class="form-group col-sm-4 col-md-2">
              <%= cb_form.label "PLU", class: "control-label col-md-12" %>
              <div class="col-md-6">
                <%= cb_form.check_box  :show_plu, { :disabled => true, class: "col-md-6"} %>
              </div>
            </div>
            <div class="form-group col-sm-4 col-md-2">
              <%= cb_form.label "Color", class: "control-label col-md-12" %>
              <div class="col-md-6">
                <%= cb_form.check_box :show_color, { :disabled => true, class: "col-md-6"} %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-xs-12">
            <%= cb_form.label :label_one, class: "control-label" %>
            <%= cb_form.text_area :label_one, class: "form-control", :disabled => true, rows: 5 %>
          </div>
          <div class="col-md-6 col-xs-12">
            <%= cb_form.label :label_two, class: "control-label" %>
            <%= cb_form.text_area :label_two, class: "form-control", :disabled => true, rows: 5 %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-xs-12">
            <%= cb_form.label :footer_one, class: "control-label" %>
            <%= cb_form.text_area :footer_one, class: "form-control", :disabled => true, rows: 7 %>
          </div>
          <div class="col-md-6 col-xs-12">
            <%= cb_form.label :footer_two, class: "control-label" %>
            <%= cb_form.text_area :footer_two, class: "form-control", :disabled => true, rows: 7 %>
          </div>

        </div>
  </div>
</div>

   <!-- hidden_field(:collections_bill, :customer_id) %>-->

<% end %>
<script type="text/javascript">
   $('[type="checkbox"]').bootstrapSwitch('size', 'mini');
</script>

app/views/collections_bills/adjust.html.erb
<%= content_for :javascripts do %>
  <script type="text/javascript">

  </script>
<% end %>

<h1>Bill Adjustments</h1>

<%= render 'adjust_form' %>

<%= link_to 'Show', greenhouse_sale_collections_bill_path(@greenhouse.id, @sale.id, @collections_bill.id) %> |
<%= link_to 'Back', greenhouse_sale_path(@greenhouse.id, @sale.id) %>

app/views/collections_bills/edit.html.erb
<h1>Editing Collections Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', greenhouse_sale_collections_bill_path(@greenhouse.id, @sale.id, @collections_bill.id) %> |
<%= link_to 'Back', greenhouse_sale_path(@greenhouse.id, @sale.id) %>

app/views/collections_bills/index.html.erb
<h1>Listing Collections Bills</h1>

<table>
  <thead>
    <tr>
      <th>Sale</th>
      <th>Invoice number</th>
      <th>Shipment consecutive</th>
      <th>Po number</th>
      <th>Payment terms</th>
      <th>Bol date</th>
      <th>Total amt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections_bills.each do |collections_bill| %>
      <tr>
        <td><%= collections_bill.sale_id %></td>
        <td><%= collections_bill.invoice_number %></td>
        <td><%= collections_bill.ship_number %></td>
        <td><%= collections_bill.po_number %></td>
        <td><%= collections_bill.payment_terms %></td>
        <td><%= collections_bill.bol_date %></td>
        <td><%= collections_bill.total_amt %></td>
        <td><%= link_to 'Show', collections_bill %></td>
        <td><%= link_to 'Edit', edit_collections_bill_path(collections_bill) %></td>
        <td><%= link_to 'Destroy', collections_bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collections bill', new_collections_bill_path %>

app/views/collections_bills/new.html.erb
<h1>New Collections Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', greenhouse_sale_path(@greenhouse.id, @sale.id) %>

app/views/collections_bills/show.html.erb
<%= button_to "Facturar", to_invoice_path(@collections_bill)  %>



<p>
  <strong>Sale:</strong>
  <%= @collections_bill.sale_id %>
</p>

<p>
  <strong>Invoice number:</strong>
  <%= @collections_bill.invoice_number %>
</p>

<p>
  <strong>Shipment consecutive:</strong>
  <%= @collections_bill.ship_number %>
</p>

<p>
  <strong>Po number:</strong>
  <%= @collections_bill.po_number %>
</p>

<p>
  <strong>Sold to:</strong>
  <%= @customer.business_name %>
</p>

<p>
  <strong>Bill to:</strong>
  <%= @customer.business_name %>
</p>

<p>
  <strong>Payment terms:</strong>
  <%= @collections_bill.payment_terms %>
</p>

<p>
  <strong>Bol date:</strong>
  <%= @collections_bill.bol_date %>
</p>

<p>
  <strong>Total amt:</strong>
  <%= @collections_bill.total_amt %>
</p>

<p>
  <strong>proforma_invoice:</strong>
  <%= @collections_bill.proforma_invoice %>
</p>

<p>
  <strong>Label 1:</strong>
  <%= @collections_bill.label_one %>
</p>

<p>
  <strong>label_two:</strong>
  <%= @collections_bill.label_two %>
</p>

<p>
  <strong>bill_of_lading:</strong>
  <%= @collections_bill.bill_of_lading %>
</p>

<p>
  <strong>thermograph:</strong>
  <%= @collections_bill.thermograph           %>
</p>

<p>
  <strong>footer_one:</strong>
  <%= @collections_bill.footer_one %>
</p>

<p>
  <strong>footer_two:</strong>
  <%= @collections_bill.footer_two %>
</p>

<p>
  <strong>show_color:</strong>
  <%= @collections_bill.show_color %>
</p>

<p>
  <strong>show_plu:</strong>
  <%= @collections_bill.show_plu %>
</p>

<p>
  <strong>show_count_type:</strong>
  <%= @collections_bill.show_count_type %>
</p>

<p>
  <strong>show_pkg_type:</strong>
  <%= @collections_bill.show_pkg_type %>
</p>

<p>
  <strong>show_bag_type:</strong>
  <%= @collections_bill.show_bag_type %>
</p>

<%= link_to 'Edit', edit_greenhouse_sale_collections_bill_path(@greenhouse.id, @sale.id, @collections_bill.id) %> |
 <%= link_to 'Back', greenhouse_sale_path(@greenhouse.id, @sale.id) %>